name: test
on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    branches: [main]
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3.1.0
        with:
          go-version: "1.19"
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Restore Go build cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-v1-${{ github.run_id }}
      - name: Get dependencies
        run: go mod download
      - name: Test
        run: make test